[package]
name = "synscript"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
# syntect = "4.7.0"
syntect = { git = "https://github.com/slimsag/syntect" }
